import { COMPANIES, COMPANY_ALIASES } from '../../constants/companies';
import { UPLOAD_DATE_FIELD } from '../../schema';
import type { CompanyOutputColumn, CompanyOutputSchema } from './types';

function outputColumn(header: string, ...sourceFields: string[]): CompanyOutputColumn {
  return { header, sourceFields };
}

const orderNumber = ['주문번호'];
const itemOrderNumber = ['상품주문번호(아이템)'];
const orderedAt = ['주문일시'];
const shippingRequestedAt = ['배송(출하)지시일'];
const salesChannel = ['판매채널'];
const shippingBase = ['출고지'];
const trackingNumber = ['운송장번호'];
const ordererName = ['주문자명'];
const ordererPhone = ['주문자연락처'];
const recipientName = ['수취인명'];
const recipientMobile = ['수취인연락처(휴대폰)', '수취인연락처(전화)'];
const recipientPhone = ['수취인연락처(전화)', '수취인연락처(휴대폰)'];
const postalCode = ['우편번호'];
const address = ['배송주소'];
const message = ['배송메세지'];
const productName = ['상품명'];
const optionName = ['옵션명'];
const productCode = ['판매자(협력사)상품코드', '상품코드'];
const quantity = ['수량'];
const carrier = ['택배사'];

const standardFulfillmentColumns = [
  outputColumn('날짜', UPLOAD_DATE_FIELD),
  outputColumn('판매처', ...salesChannel),
  outputColumn('출고지', ...shippingBase),
  outputColumn('상품주문번호1', ...orderNumber),
  outputColumn('상품주문번호2', ...itemOrderNumber),
  outputColumn('옵션', ...optionName),
  outputColumn('운송장번호', ...trackingNumber),
  outputColumn('주문자성명', ...ordererName),
  outputColumn('받는분성명', ...recipientName),
  outputColumn('받는분전화번호', ...recipientMobile),
  outputColumn('받는분기타연락처', ...recipientPhone),
  outputColumn('받는분 주소', ...address),
  outputColumn('품목명', ...productName),
  outputColumn('수량', ...quantity),
  outputColumn('배송메세지', ...message),
  outputColumn('담당자명'),
  outputColumn('박스사이즈'),
];

export const COMPANY_OUTPUT_SCHEMAS: CompanyOutputSchema[] = [
  {
    id: 'fruit-preserves',
    name: COMPANIES.FRUIT_PRESERVES,
    aliases: COMPANY_ALIASES[COMPANIES.FRUIT_PRESERVES],
    columns: standardFulfillmentColumns,
  },
  {
    id: 'daewoong-morningcom',
    name: COMPANIES.DAEWOONG_MORNINGCOM,
    aliases: COMPANY_ALIASES[COMPANIES.DAEWOONG_MORNINGCOM],
    columns: standardFulfillmentColumns,
  },
  {
    id: 'maison-de-module',
    name: COMPANIES.MAISON_DE_MODULE,
    aliases: COMPANY_ALIASES[COMPANIES.MAISON_DE_MODULE],
    columns: [
      outputColumn('발주일자', UPLOAD_DATE_FIELD),
      outputColumn('생산처1'),
      outputColumn('거래처', ...salesChannel),
      outputColumn('생산처2'),
      outputColumn('배송처', ...shippingBase),
      outputColumn('쇼핑몰', ...salesChannel),
      outputColumn('수취인', ...recipientName),
      outputColumn('연락처1', ...recipientMobile),
      outputColumn('연락처2', ...recipientPhone),
      outputColumn('우편번호', ...postalCode),
      outputColumn('배송지', ...address),
      outputColumn('상품명[쇼핑몰]', ...productName),
      outputColumn('상품명[업체]', ...productName),
      outputColumn('수량', ...quantity),
      outputColumn('지정일', ...shippingRequestedAt),
      outputColumn('상담내용'),
      outputColumn('고객요청사항', ...message),
      outputColumn('주문번호', ...orderNumber),
      outputColumn('CS'),
      outputColumn('박스수량'),
      outputColumn('정산금액', '공급가(정산단가)', '고객결제금액'),
    ],
  },
  {
    id: 'biyott-u',
    name: COMPANIES.BIWIT_U,
    aliases: COMPANY_ALIASES[COMPANIES.BIWIT_U],
    columns: [
      outputColumn('주문일자', ...orderedAt),
      outputColumn('주문번호', ...orderNumber),
      outputColumn('주문자 성함', ...ordererName),
      outputColumn('주문자 연락처', ...ordererPhone),
      outputColumn('제품명', ...productName),
      outputColumn('옵션명', ...optionName),
      outputColumn('수량', ...quantity),
      outputColumn('수령인 성함', ...recipientName),
      outputColumn('수령인 연락처', ...recipientMobile),
      outputColumn('수령인 통관번호'),
      outputColumn('우편번호', ...postalCode),
      outputColumn('수령인 주소', ...address),
      outputColumn('배송 메시지', ...message),
      outputColumn('택배사', ...carrier),
      outputColumn('운송장번호', ...trackingNumber),
      outputColumn('판매채널', ...salesChannel),
    ],
  },
  {
    id: 'sinuiju-sundae',
    name: COMPANIES.SINUIJU_SUNDAE,
    aliases: COMPANY_ALIASES[COMPANIES.SINUIJU_SUNDAE],
    columns: [
      outputColumn('주문자성명', ...ordererName),
      outputColumn('주문자전화번호', ...ordererPhone),
      outputColumn('주문자주소(전체, 분할)'),
      outputColumn('받는분성명', ...recipientName),
      outputColumn('받는분전화번호', ...recipientMobile),
      outputColumn('받는분기타연락처', ...recipientPhone),
      outputColumn('받는분주소(전체, 분할)', ...address),
      outputColumn('고객주문번호', ...orderNumber),
      outputColumn('운송장번호', ...trackingNumber),
      outputColumn('품목명', ...productName),
      outputColumn('내품수량', ...quantity),
      outputColumn('사용안함'),
      outputColumn('배송메세지1', ...message),
    ],
  },
  {
    id: 'okay-duck',
    name: COMPANIES.OKAY_DUCK,
    aliases: COMPANY_ALIASES[COMPANIES.OKAY_DUCK],
    columns: [
      outputColumn('수집몰', ...salesChannel),
      outputColumn('주문일', ...orderedAt),
      outputColumn('수집일', UPLOAD_DATE_FIELD),
      outputColumn('상품명', ...productName),
      outputColumn('옵션', ...optionName),
      outputColumn('수량', ...quantity),
      outputColumn('주문자명', ...ordererName),
      outputColumn('연락처1', ...ordererPhone),
      outputColumn('연락처2'),
      outputColumn('수취인', ...recipientName),
      outputColumn('수취인연락처1', ...recipientMobile),
      outputColumn('수취인연락처2', ...recipientPhone),
      outputColumn('우편번호', ...postalCode),
      outputColumn('주소', ...address),
      outputColumn('배송메세지', ...message),
      outputColumn('택배사', ...carrier),
      outputColumn('송장번호', ...trackingNumber),
    ],
  },
  {
    id: 'yoon-jonghee-tteokbang',
    name: COMPANIES.YOON_JONGHEE_TTEOKBANG,
    aliases: COMPANY_ALIASES[COMPANIES.YOON_JONGHEE_TTEOKBANG],
    columns: [
      outputColumn('출하지시번호', '출하지시번호', ...orderNumber),
      outputColumn('품목명', ...productName),
      outputColumn('수량', ...quantity),
      outputColumn('수취인명', ...recipientName),
      outputColumn('수취인 전화번호', ...recipientPhone),
      outputColumn('수취인 핸드폰번호', ...recipientMobile),
      outputColumn('우편번호', ...postalCode),
      outputColumn('주소', ...address),
      outputColumn('배송메세지', ...message),
      outputColumn('택배사', ...carrier),
      outputColumn('송장번호', ...trackingNumber),
    ],
  },
  {
    id: 'jeober-korea',
    name: COMPANIES.JEOBER_KOREA,
    aliases: COMPANY_ALIASES[COMPANIES.JEOBER_KOREA],
    columns: standardFulfillmentColumns,
  },
  {
    id: 'jeju-hyanggi',
    name: COMPANIES.JEJU_HYANGGI,
    aliases: COMPANY_ALIASES[COMPANIES.JEJU_HYANGGI],
    columns: [
      outputColumn('날짜', UPLOAD_DATE_FIELD),
      outputColumn('발주처', ...salesChannel),
      outputColumn('운송장식별번호', '운송장식별번호'),
      outputColumn('주문번호', ...orderNumber),
      outputColumn('수취인', ...recipientName),
      outputColumn('수취인핸드폰', ...recipientMobile),
      outputColumn('수취인전화번호', ...recipientPhone),
      outputColumn('우편번호', ...postalCode),
      outputColumn('수취인주소', ...address),
      outputColumn('배송메세지', ...message),
      outputColumn('택배사', ...carrier),
      outputColumn('운송장번호', ...trackingNumber),
      outputColumn('상품명', ...productName),
      outputColumn('옵션', ...optionName),
      outputColumn('수량', ...quantity),
    ],
  },
  {
    id: 'e-hangeul',
    name: COMPANIES.TAHYANGGOL,
    aliases: COMPANY_ALIASES[COMPANIES.TAHYANGGOL],
    columns: [
      outputColumn('주문일시', ...orderedAt),
      outputColumn('판매채널', ...salesChannel),
      outputColumn('상품주문번호', ...itemOrderNumber),
      outputColumn('주문번호', ...orderNumber),
      outputColumn('택배사', ...carrier),
      outputColumn('송장번호', ...trackingNumber),
      outputColumn('판매자 상품코드', ...productCode),
      outputColumn('상품명', ...productName),
      outputColumn('옵션정보', ...optionName),
      outputColumn('수량', ...quantity),
      outputColumn('수취인명', ...recipientName),
      outputColumn('수취인연락처1', ...recipientMobile),
      outputColumn('수취인연락처2', ...recipientPhone),
      outputColumn('우편번호', ...postalCode),
      outputColumn('통합배송지', ...address),
      outputColumn('배송메시지', ...message),
      outputColumn('구매자명', ...ordererName),
      outputColumn('구매자연락처', ...ordererPhone),
    ],
  },
  {
    id: 'french-luxury',
    name: COMPANIES.FRENCH_LUXURY,
    aliases: COMPANY_ALIASES[COMPANIES.FRENCH_LUXURY],
    columns: [
      outputColumn('주문번호', ...orderNumber),
      outputColumn('배송방법', '배송방법'),
      outputColumn('택배사', ...carrier),
      outputColumn('송장번호', ...trackingNumber),
      outputColumn('주문자', ...ordererName),
      outputColumn('상품이름', ...productName),
      outputColumn('상품옵션정보', ...optionName),
      outputColumn('수량', ...quantity),
      outputColumn('수취인명', ...recipientName),
      outputColumn('수취인연락처', ...recipientMobile),
      outputColumn('배송지', ...address),
      outputColumn('우편번호', ...postalCode),
      outputColumn('배송메시지', ...message),
      outputColumn('비고'),
      outputColumn('상품주문번호', ...itemOrderNumber),
      outputColumn('비고'),
      outputColumn('원 주문번호', '원주문번호'),
      outputColumn('발송인', '판매자(협력사/브랜드)명'),
      outputColumn('발송인연락처'),
    ],
  },
  {
    id: 'print-bakery',
    name: COMPANIES.PRINT_BAKERY,
    aliases: COMPANY_ALIASES[COMPANIES.PRINT_BAKERY],
    columns: [
      outputColumn('주문일시', ...orderedAt),
      outputColumn('판매채널', ...salesChannel),
      outputColumn('상품주문번호', ...itemOrderNumber),
      outputColumn('주문번호', ...orderNumber),
      outputColumn('택배사', ...carrier),
      outputColumn('송장번호', ...trackingNumber),
      outputColumn('상품명', ...productName),
      outputColumn('옵션정보', ...optionName),
      outputColumn('수량', ...quantity),
      outputColumn('수취인명', ...recipientName),
      outputColumn('수취인연락처1', ...recipientMobile),
      outputColumn('수취인연락처2', ...recipientPhone),
      outputColumn('우편번호', ...postalCode),
      outputColumn('통합배송지', ...address),
      outputColumn('배송메시지', ...message),
      outputColumn('구매자명', ...ordererName),
      outputColumn('구매자연락처', ...ordererPhone),
      outputColumn('설치요청일', ...shippingRequestedAt),
    ],
  },
  {
    id: 'heymil',
    name: COMPANIES.HEYMIL,
    aliases: COMPANY_ALIASES[COMPANIES.HEYMIL],
    columns: [
      outputColumn('출하지시번호', '출하지시번호', ...orderNumber),
      outputColumn('품목명', ...productName),
      outputColumn('채널명', ...salesChannel),
      outputColumn('수량', ...quantity),
      outputColumn('판매단가', '판매가'),
      outputColumn('옵션총금액', '고객결제금액'),
      outputColumn('수취인명', ...recipientName),
      outputColumn('수취인 전화번호', ...recipientPhone),
      outputColumn('수취인 핸드폰번호', ...recipientMobile),
      outputColumn('우편번호', ...postalCode),
      outputColumn('주소', ...address),
      outputColumn('배송메세지', ...message),
      outputColumn('배송비'),
      outputColumn('발송인명', '판매자(협력사/브랜드)명'),
      outputColumn('발송인 우편번호'),
      outputColumn('발송인 주소', ...shippingBase),
      outputColumn('발송인 연락처'),
      outputColumn('주문자명', ...ordererName),
      outputColumn('주문자 연락처', ...ordererPhone),
      outputColumn('택배사', ...carrier),
      outputColumn('송장번호', ...trackingNumber),
    ],
  },
];
